<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Macd_Ordersbtn</name>
   <tag></tag>
   <elementGuidId>6eac8c74-4f08-4517-a31b-e34ead17c49c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a//span[contains(text(),'Orders')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
