<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OrderBtn</name>
   <tag></tag>
   <elementGuidId>198d385b-fd29-43d8-a5af-5b87f05c5a96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a//span[contains(text(),'Orders')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
