<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BillingFrame</name>
   <tag></tag>
   <elementGuidId>09b04beb-5412-4104-8d49-a74e51526aa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='topFrame']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
