<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MainFrameSet</name>
   <tag></tag>
   <elementGuidId>f63fdd31-6407-4b05-9cf8-0ff4642ad473</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frameset[@id='pemFrames']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
