<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Account_btn</name>
   <tag></tag>
   <elementGuidId>2e36e4e6-12e9-4747-8eed-6562421abb37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a//strong[contains(text(),'Account')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
